<?php

DEFINE('ERROR_CODE_INVALID_PARAMETERS',   1001);
DEFINE('ERROR_CODE_NO_ENCRYPTED_FILES',   1003);

DEFINE('UPLOAD_PATH',   'uploads/');

DEFINE('USER_MESSAGE_SUCCESS', 0);
DEFINE('USER_MESSAGE_WARNING', 1);
DEFINE('USER_MESSAGE_ERROR', 2);